# Generated by Django 3.2.13 on 2022-08-14 20:34
from django.contrib.postgres.operations import TrigramExtension
import block_9.indexes.task_1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes_task_1', '0002_auto_20220808_1124'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['fname', 'iname', 'oname'], name='indexes_emp_fname_1395cf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['country'], name='indexes_emp_country_caf6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=block_9.indexes.task_1.models.UpperGinIndex(fields=['additional_info'], name='additional_info_gin_index', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['begin'], name='indexes_emp_begin_a3eff6_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['end'], name='indexes_emp_end_be87f4_idx'),
        ),
    ]
